[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

# [target.x86_64-unknown-linux-musl]
# rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=-lm"]

[build]
rustflags = ["--cfg=has_std"]